version: '3.8'

services:
  brians-ad-service:
    container_name: brians-ad-service
    image: brhv/psuadservice
    restart: unless-stopped
    ports:
      - 8084:80

  ad-service:
    container_name: ad-service
    build:
      context: ./AdService
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - brians-ad-service
      - ad-service-redis
    restart: unless-stopped

  ad-service-redis:
    image: redis:5.0-alpine
    container_name: ad-service-redis
    command: --port 6380
    ports:
      - 6380:6380
    expose:
      - 6380
    volumes:
      - ad-service-redis-data:/data

  booking-service:
    image: ${DOCKER_REGISTRY-}booking-service
    build:
      context: .
      dockerfile: BookingService/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - postgres

  parking-ads-api:
    image: ${DOCKER_REGISTRY-}parking-ads-api
    build:
      context: .
      dockerfile: ParkingAdsApi/Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - postgres

  parking-service:
    image: ${DOCKER_REGISTRY-}parking-service
    build:
      context: .
      dockerfile: ParkingService/Dockerfile
    ports:
      - "8003:80"
    depends_on:
      - postgres

  postgres:
    container_name: parking-ads-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    container_name: parking-ads-redis

  adminer:
    image: adminer:4.7.6
    container_name:  parking-ads-adminer
    ports:
      - "1100:8080"

volumes:
  ad-service-redis-data:
  db:
    driver: local