version: '3.7'

services:
  redis:
    container_name: redis
    image: 'redis:6.0.6'
    ports:
      - '127.0.0.1:6379:6379/tcp'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    container_name: redisinsight
    image: 'redislabs/redisinsight:latest'
    ports:
      - '127.0.0.1:8001:8001'
  
  parking-service-repository-api:
    container_name: parking-service-repository-api
    image: 'brhv/psuparkingservice'
    ports:
      - '8083:80'